name: Deploy to Azure
on:
  push:
    branches: [ development ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Zip artifact for deployment
      run: |
        zip -r release.zip . \
          -x '.git/*' \
          -x '.github/*' \
          -x 'antenv/*' \
          -x '__pycache__/*' \
          -x '*.pyc' \
          -x '*.pyo'

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: cartesian-sportwear-backend-dev
        publish-profile: ${{ secrets.PUBLISH_PROFILE_DEV}}
        package: release.zip
